const publications = [
  {
    title:
      "A dirac-frenkel-onsager principle: instantaneous residual minimization with gauge momentum for nonlinear parametrizations of PDE solutions",
    authors: ["Matteo Raviola", "Benjamin Peherstorfer"],
    venue: "Manuscript submitted to ICML 2026",
    status: "Under review",
    year: 2026,
    links: [],
    abstract:
      "Dirac-Frenkel instantaneous residual minimization evolves nonlinear parametrizations of PDE solutions in time, but ill-conditioning can render the parameter dynamics non-unique. We interpret this non-uniqueness as a gauge freedom: nullspace directions that leave the time derivative unchanged can be used to select better-conditioned parameter velocities. Building on Onsager's minimum-dissipation principle, we introduce a history variable, interpretable as momentum, and inject it only along the nullspace directions. The resulting Dirac-Frenkel-Onsager dynamics preserve instantaneous residual minimization, in contrast to standard regularization that can introduce bias, while promoting temporally smooth parameter evolutions. Examples demonstrate that the approach leads to increased robustness in singular and near-singular regimes.",
    image: "assets/dfo.gif",
  },
  {
    title: "Stochastic gradient with least-squares control variates",
    authors: ["Fabio Nobile", "Matteo Raviola", "Nathan Schaeffer"],
    venue: "arXiv preprint",
    status: "2025",
    year: 2025,
    links: [
      {
        label: "arXiv",
        href: "https://arxiv.org/abs/2507.20981",
      },
    ],
    abstract:
      "This paper proposes a variance-reduced stochastic gradient method for optimization problems posed as expectations over continuously distributed random variables. The key idea is to fit a linear control variate to past gradient evaluations with weighted discrete least squares, reducing variance without losing computational efficiency. The paper proves sublinear convergence for strongly convex objectives and tests the method on random PDE-constrained optimization problems.",
    image: "assets/FixedSG-LSCV_deg_comparison_beststep.png",
  },
  {
    title: "A function approximation algorithm using multilevel active subspaces",
    authors: ["Fabio Nobile", "Matteo Raviola", "Raul Tempone"],
    venue: "Monte Carlo and Quasi-Monte Carlo Methods 2024, Springer",
    status: "2025, to appear",
    year: 2025,
    links: [
      {
        label: "arXiv",
        href: "https://arxiv.org/abs/2501.12867",
      },
    ],
    abstract:
      "The paper introduces a multilevel active subspace method that combines samples computed at different accuracies to identify low-dimensional structure more cheaply than standard active subspaces. It then uses these level-dependent subspaces for optimally weighted least-squares polynomial approximation, with an adaptive procedure that selects both the subspace dimensions and the polynomial spaces. Numerical experiments on random PDEs show that the approach preserves accuracy while lowering computational cost.",
    image: "assets/logn_Cds_d100_P1_alpha2_L7.png",
  },
  {
    title:
      "Network-based kinetic models: Emergence of a statistical description of the graph topology",
    authors: ["Marco Nurisso", "Matteo Raviola", "Andrea Tosin"],
    venue: "European Journal of Applied Mathematics",
    status: "2024",
    year: 2024,
    links: [
      {
        label: "DOI",
        href: "https://doi.org/10.1017/S0956792524000020",
      },
    ],
    abstract:
      "This work develops kinetic equations for collective dynamics generated by graph-mediated pairwise interactions in multi-agent systems. For large graphs and suitable interaction classes, it shows that the network can be represented statistically through degree distributions embedded in a Boltzmann-type equation, supporting the idea that connectivity is the main graph feature that needs to be retained. The theory is validated numerically using real social-network data.",
    image: "assets/action-reaction-twitter.png",
  },
  {
    title: "Opinion polarization in social networks",
    authors: ["Nadia Loy", "Matteo Raviola", "Andrea Tosin"],
    venue: "Philosophical Transactions of the Royal Society A",
    status: "2022",
    year: 2022,
    links: [
      {
        label: "DOI",
        href: "https://doi.org/10.1098/rsta.2021.0158",
      },
    ],
    abstract:
      "The paper studies opinion formation on social networks with a Boltzmann-type kinetic model that incorporates a statistical description of user connectivity rather than assuming a regular lattice. It derives analytical conditions for a polarization switch, where the long-time mean opinion changes sign relative to the initial one, and shows that such a switch requires a nonzero correlation between agents' connectivity and their initial opinions. Monte Carlo simulations are used to confirm the theory.",
    image:
      "assets/Asymptotic-opinion-distribution-of-the-Ochrombel-simplification_W640.jpg",
  },
  {
    title:
      "Training Kernel Neural ODEs with optimal control and Riemannian optimization",
    authors: ["Matteo Raviola"],
    venue: "Master's thesis, Politecnico di Torino",
    status: "2022",
    year: 2022,
    links: [
      {
        label: "ResearchGate",
        href: "https://www.researchgate.net/publication/364342042_Training_Kernel_Neural_ODEs_with_Optimal_Control_and_Riemannian_optimization",
      },
    ],
    abstract:
      "The flexibility of Neural Networks makes them a formidable tool to perform numerous kinds of tasks, however their training keeps proving to be a computationally challenging optimization problem. This talk focuses on a specific kind of Neural ODEs, Kernel Neural ODEs (KerODEs), where the usual parametric non-linearities are replaced by elements of a reproducing kernel Hilbert space (RKHS) fixed a priori. We propose and numerically explore methodologies to overcome the issues of traditional gradient-based algorithms for the optimization of KerODE parameters in the context of a regression task. In particular, we first exploit the dynamical systems perspective of Deep Learning to link the training problem to an optimal control problem and develop algorithms inspired by time-parallel ODE integration techniques to speed up optimization. As an alternative approach, we formally introduce a differential structure on the family of mappings realized by KerODEs, enabling the use of continuous Riemanninan optimization techniques to solve the training problem. This furnishes a new and compelling perspective on Neural ODEs as the realization of a Riemannian gradient/Newton flow which, in practice, leads to layer-by-layer optimization techniques thus alleviating the cost per iteration of classic approaches.",
    image: "assets/KNNet_arc2D_regdeg10_predictionintime3D.png",
  },
];

function renderAuthor(name) {
  if (name === "Matteo Raviola") {
    return `<span class="me">${name}</span>`;
  }

  return name;
}

function renderPublication(publication) {
  const hasImage = Boolean(publication.image);
  const abstractId = `abstract-${publication.year}-${publication.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")}`;
  const linksMarkup = publication.links
    .map((link) => `<a href="${link.href}">${link.label}</a>`)
    .join("");

  return `
    <article class="publication-card ${hasImage ? "has-image" : ""}">
      ${
        hasImage
          ? `
            <div class="publication-media">
              <img src="${publication.image}" alt="${publication.title}">
            </div>
          `
          : ""
      }
      <div class="publication-content">
        <p class="publication-title">${publication.title}</p>
        <p class="publication-authors">${publication.authors
          .map(renderAuthor)
          .join(", ")}</p>
        <p class="publication-venue">${publication.venue}</p>
        <p class="publication-status">${publication.status}</p>
        ${
          linksMarkup
            ? `<div class="publication-links">${linksMarkup}</div>`
            : ""
        }
        ${
          publication.abstract
            ? `
              <button
                type="button"
                class="abstract-toggle"
                aria-expanded="false"
                aria-controls="${abstractId}"
              >
                abstract
              </button>
              <div id="${abstractId}" class="publication-abstract" hidden>
                <p>${publication.abstract}</p>
              </div>
            `
            : ""
        }
      </div>
    </article>
  `;
}

function mountPublications() {
  const container = document.getElementById("publications-list");

  if (!container) {
    return;
  }

  container.innerHTML = publications.map(renderPublication).join("");

  container.addEventListener("click", (event) => {
    const button = event.target.closest(".abstract-toggle");

    if (!button) {
      return;
    }

    const abstract = document.getElementById(button.getAttribute("aria-controls"));
    const expanded = button.getAttribute("aria-expanded") === "true";

    if (!abstract) {
      return;
    }

    button.setAttribute("aria-expanded", String(!expanded));
    button.textContent = expanded ? "abstract" : "hide abstract";
    abstract.hidden = expanded;
  });
}

mountPublications();
